#!/bin/bash
#SBATCH --job-name="test"
#SBATCH --partition="main"
#SBATCH -n 20
#SBATCH --ntasks-per-node=20
#SBATCH --output=vasp-srun.out 
#SBATCH --error=vasp-srun.err
#SBATCH --mem-per-cpu=2000M
#SBATCH --time=24:00:00


module purge
ml intel/2018.04 VASP/5.4.4


export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export LC_ALL=C

EXEC=vasp_std
BINVASP="${EXEC}"

cp INCAR-100 INCAR
srun $BINVASP
cp OUTCAR OUTCAR-100
cp INCAR-200 INCAR
srun $BINVASP
cp OUTCAR OUTCAR-200
cp INCAR-300 INCAR
srun $BINVASP
cp OUTCAR OUTCAR-300
cp INCAR-400 INCAR
srun $BINVASP
cp OUTCAR OUTCAR-400
cp INCAR-500 INCAR
srun $BINVASP
cp OUTCAR OUTCAR-500
cp INCAR-600 INCAR
srun $BINVASP
cp OUTCAR OUTCAR-600
cp INCAR-700 INCAR
srun $BINVASP
cp OUTCAR OUTCAR-700
cp INCAR-800 INCAR
srun $BINVASP
cp OUTCAR OUTCAR-800


rm  CONTCAR  CHG CHGCAR WAVECAR EIGENVAL PROCAR DOSCAR OSZICAR PCDAT XDATCAR REPORT
